### ISSUE TITLE
Terms for booking the rooms should be available

### ISSUE THREAD

**Issue by Sponken** [cthit/bookIT-node#16]

**Comment by molleer** [comment]
**How?:**
- [ ] Copy P.R.I.T.s terms of service document into a pop-up dialogue which shows up when pressing "Terms and conditions" link
- [ ] Add `accepted_terms` entry in the [database migration schema](https://github.com/cthit/bookIT-node/blob/main/backend/migrations/1628185424194_event.js), the [ts model type definition](https://github.com/cthit/bookIT-node/blob/main/backend/src/models/event.ts) and the [Graphql schema](https://github.com/cthit/bookIT-node/blob/main/backend/src/schemas/v1/event.gql)
- [ ] Query `accepted_terms` in the event repository
- [ ] Require `accepted_terms` to be true in the event service when creating a new event
- [ ] Add "I agree" checkbox in the new event form

**Comment by Supergamer1337** [comment]
Closed in #43
