### ISSUE TITLE
booking form gets wider when adding a party report

### ISSUE THREAD

**Issue by ide-1** [cthit/bookIT-node#17]

**Comment by molleer** [comment]
**How?:** Set the width of the new event form to always be wide

**Comment by ide-1** [comment]
either that or line the up the input fields for the party report vertically instead of horisontally

**Comment by molleer** [comment]
Could just use the standard `DigitEditData` component, but its worse for non-phone users and it might be more difficult to show/hide components like the party report things

**Comment by Supergamer1337** [comment]
Could also make it look like this instead
![image](https://user-images.githubusercontent.com/46903500/172366908-5caa0fd1-7dde-45ef-8678-429ccd8f0cff.png)

That way it seems more like the name is a "title" for the information, while keeping the form just as wide as previously. Of course, it's a compromise, but I just think it might look/work the best.

**Comment by Supergamer1337** [comment]
This was fixed in #49 as a side effect of the other column.
