### ISSUE TITLE
User should be able to choose as what commitee to book as

### ISSUE THREAD

**Issue by Hoidi** [cthit/bookIT-node#3]

**Comment by molleer** [comment]
**How?:**
- [ ] Add `booked_by` and `booked_as` entry in the database. Done by altering the [event migration schema](https://github.com/cthit/bookIT-node/blob/main/backend/migrations/1628185424194_event.js)
- [ ] Add `booked_by` and `booked_as` in the [event ts model](https://github.com/cthit/bookIT-node/blob/main/backend/src/models/event.ts)
- [ ] Add `booked_by` and `booked_as` in the [graphql event schema](https://github.com/cthit/bookIT-node/blob/main/backend/src/schemas/v1/event.gql)
- Add `booked_by` and `booked_as` in the [event repository](https://github.com/cthit/bookIT-node/blob/main/backend/src/repositories/event.repository.ts)
    - [ ] When requesting data from the database with the
    - [ ] When creating new events
- [ ] Run the application and see if you can create a new event, booked as a specific user and group, using [the Graphql UI](http://localhost:8080/api/graphql/v1)
- [ ]  Add checks in the [`createEvent` events](https://github.com/cthit/bookIT-node/blob/main/backend/src/services/event.service.ts) to see if a user is allowed to book as a specific user and group
- [ ] Add the `book_as` entry in the [`new-event` form in the frontend](https://github.com/cthit/bookIT-node/blob/main/frontend/src/use-cases/new-event/new-event.form.jsx)
- [ ] Verify that a user can book properly and that a user cannot book as another user or a group which the user is not a member of. Check in the database if the entries looks ok
- [ ] ????
- [ ] Profit
