### ISSUE TITLE
Single room bookings have wrong colour

### ISSUE THREAD

**Issue by x183** [cthit/bookIT-node#72]
![image](https://user-images.githubusercontent.com/55193662/215704307-02db493d-a726-4852-bd85-0acf7c74b8bc.png)
Sometimes, one or several of the singe-room bookings show up in the default colour instead of their room colour

**Comment by simon-wg** [comment]
I think this is fixed?

**Comment by x183** [comment]
Oops, seems like it didn't close with our issue :flushed:
